# adapted from http://sacraparental.com/2016/05/14/everyday-misogyny-122-subtly-sexist-words-women/

sexist_words ={
    'bossy': {'type': 'assertiveness'},
    'abrasive': {'type': 'assertiveness'},
    'ball-buster': {'type': 'assertiveness'},
    'aggressive': {'type': 'assertiveness'},
    'shrill': {'type': 'assertiveness'},
    'bolshy': {'type': 'assertiveness'},
    'intense': {'type': 'assertiveness'},
    'stroppy': {'type': 'assertiveness'},
    'forward': {'type': 'assertiveness'},
    'mannish': {'type': 'assertiveness'},
    'strident': {'type': 'assertiveness'},
    'know-it-all': {'type': 'assertiveness'},
    'gossip': {'type': 'behavior'},
    'dramatic': {'type': 'behavior'},
    'catty': {'type': 'behavior'},
    'bitch': {'type': 'behavior'},
    'nag': {'type': 'behavior'},
    'cold': {'type': 'behavior'},
    'icy': {'type': 'behavior'},
    'shrew': {'type': 'behavior'},
    'humorless': {'type': 'behavior'},
    'man-hater': {'type': 'behavior'},
    'banshee': {'type': 'behavior'},
    'fishwife': {'type': 'behavior'},
    'lippy': {'type': 'behavior'},
    'ditzy': {'type': 'behavior'},
    'diva': {'type': 'behavior'},
    'prima donna': {'type': 'behavior'},
    'feisty': {'type': 'behavior'},
    'ladylike': {'type': 'behavior'},
    'bubbly': {'type': 'behavior'},
    'vivaious': {'type': 'behavior'},
    'flirt': {'type': 'behavior'},
    'sass': {'type': 'behavior'},
    'chatty': {'type': 'behavior'},
    'demure': {'type': 'behavior'},
    'modest': {'type': 'behavior'},
    'emotional': {'type': 'behavior'},
    'hysterical': {'type': 'behavior'},
    'hormonal': {'type': 'behavior'},
    'menstrual': {'type': 'behavior'},
    'flaky': {'type': 'behavior'},
    'moody': {'type': 'behavior'},
    'over-sensitive': {'type': 'behavior'},
    'slut': {'type': 'sexuality'},
    'trollop': {'type': 'sexuality'},
    'frigid': {'type': 'sexuality'},
    'easy': {'type': 'sexuality'},
    'tease': {'type': 'sexuality'},
    'loose': {'type': 'sexuality'},
    'man-eater': {'type': 'sexuality'},
    'prude': {'type': 'sexuality'},
    'curvy': {'type': 'sexuality'},
    'cheap': {'type': 'sexuality'},
    'frumpy': {'type': 'sexuality'},
    'faded': {'type': 'sexuality'},
    'mousey': {'type': 'sexuality'},
    'clotheshorse': {'type': 'sexuality'},
    'spinster': {'type': 'relationship'},
    'barren': {'type': 'relationship'},
    'housewife': {'type': 'relationship'},
    'houseproud': {'type': 'relationship'},
    'soccer mom': {'type': 'relationship'},
    'mistress': {'type': 'relationship'},
    'kept woman': {'type': 'relationship'},
    'caring': {'type': 'praise'},
    'compassionate': {'type': 'praise'},
    'hard-working': {'type': 'praise'},
    'conscientious': {'type': 'praise'},
    'dependable': {'type': 'praise'},
    'diligent': {'type': 'praise'},
    'dedicated': {'type': 'praise'},
    'tactful': {'type': 'praise'},
    'interpersonal': {'type': 'praise'},
    'warm': {'type': 'praise'},
    'helpful': {'type': 'praise'}
}

print(sexist_words.keys())
